nano_arm_driver:
  ros__parameters:
    port: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A5069RR4-if00-port0
    baud: 9600
    serial_boot_wait_sec: 2.0
    command_topic: /arm_controller/joint_trajectory
    joint_state_topic: /joint_states
    joint_names: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
    joint_min_rad: [-1.57, -1.57, -1.57, -1.57, -1.57, -1.57]
    joint_max_rad: [1.57, 1.57, 1.57, 1.57, 1.57, 1.57]
    servo_home_deg: [90.0, 90.0, 90.0, 90.0, 90.0, 90.0]
    servo_direction: [1, 1, 1, 1, 1, 1]
    servo_min_deg: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    servo_max_deg: [180.0, 180.0, 180.0, 180.0, 180.0, 180.0]
    startup_positions_rad: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    write_on_startup: false
    publish_rate_hz: 20.0
    default_move_duration_sec: 0.5
    publish_joint_states: true
    debug: true
